name: kdapp17
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dynamic_color: ^1.7.0  # Make sure this is the correct/latest version


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1 # For channging app icon needed
  flutter_lints: ^4.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/kunal.png" # FOr my app icon image

flutter:
  uses-material-design: true

  assets:
    - assets/ 

